keys:
  - &tiebe age13wcwnr0nkf0vyarcxa8skn4vdqcdw3e65j9e9alcz6sdr0l69uqqgz94lh
  - &jupiter age1dnpl9h8mznl9d7pslmpv5upzah4nlwz8v085xprtxvrx7vvskpfsexuspt

creation_rules:
  - path_regex: secrets/[^/]+$
    key_groups:
    - age:
      - *tiebe
      - *jupiter