{inputs, ...}: {
  imports = [
    ./bambu-studio
    ./bitwarden
    ./claude-code
    ./discord
    ./easyeffects
    ./firefox
    ./forgecode
    ./fusion360
    ./httptoolkit
    ./intellij
    ./legcord
    ./localsend
    ./lmstudio
    ./media
    ./minecraft
    ./obsidian
    ./office
    ./opencode
    ./opendeck.nix
    ./parsec
    ./quantframe
    ./rofi
    ./steam
    ./thunderbird
    ./vencord
    ./vscode
    ./wezterm
  ];
}
