name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

permissions:
  contents: write
  pull-requests: write

jobs:
  lockfile:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        run: nix flake update
        env: 
          NIX_CONFIG: "access-tokens = github.com=${{ secrets.PAT_GITHUB }}"
      - name: Install jq
        run: apt update && apt install -y jq
      - name: Create PR
        uses: https://github.com/maxking/forgejo-create-pr@966d9dd4211f0f588abce5144f4138941f31099f
        with:
          commit-message: "chore(flake): bump inputs"
          commit-user: 'Tiebe Groosman'
          commit-email: 'tiebe.groosman@gmail.com'
          pr-branch: "update-flake-lock"
          pr-title: "chore(flake): bump inputs"
          pr-body: ""
          pr-automerge: true
          token: ${{ secrets.TOKEN }}
