# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["ntfs"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/71f5521b-9fb6-4ebe-9a61-a4b46c57ea43";
    fsType = "btrfs";
    options = ["subvol=root" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/71f5521b-9fb6-4ebe-9a61-a4b46c57ea43";
    fsType = "btrfs";
    options = ["subvol=home" "noatime"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/71f5521b-9fb6-4ebe-9a61-a4b46c57ea43";
    fsType = "btrfs";
    options = ["subvol=persist" "noatime"];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/71f5521b-9fb6-4ebe-9a61-a4b46c57ea43";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/71f5521b-9fb6-4ebe-9a61-a4b46c57ea43";
    fsType = "btrfs";
    options = ["subvol=log" "noatime" "compress=zstd"];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/020D-1E55";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/run/media/tiebe/Data" = {
    device = "/dev/disk/by-uuid/5dd4afd3-69b9-e6b1-9162-0f07bc9cca28";
    fsType = "btrfs";
  };

  fileSystems."/run/media/tiebe/Games" = {
    device = "/dev/disk/by-uuid/f1caf7db-1e19-dda4-d177-45e2f0feb0b8";
    fsType = "btrfs";
  };

  # TODO!! when switching to erase your darlings, make sure to first recreate root snapshot with /run/media folders for mounts. otherwise no boot

  swapDevices = [
    {device = "/dev/disk/by-uuid/a4b4def0-6197-4054-ba85-66ddec0a554b";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u1i5.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
