{
  config,
  lib,
  ...
}: let
  inherit (lib) mkIf;
  cfg = config.tiebe.desktop.hyprland;
  darlings = config.tiebe.system.boot.darlings;
in {
  config = mkIf (darlings.enable && cfg.enable) {
    # Hyprland, waybar, and swaync configs are fully declarative
    # (generated by home-manager / nix wrappers), so nothing to persist.
  };
}
