# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install packages
        run: |
          python -m pip install requests pyrage

      - name: Create new key
        env:
          TS_CLIENT_ID: "{{ secrets.TS_CLIENT_ID }}"
          TS_CLIENT_SECRET: "{{ secrets.TS_CLIENT_SECRET }}"
        run: |
          import requests
          from pyrage import encrypt, ssh, x25519
          import json
          import subprocess
          import os
          
          def get_tailscale_api_token(client_id: str, client_secret: str):
              """
              Authenticate with the tailscale oauth api to retrieve an api token
              """
              url = "https://api.tailscale.com/api/v2/oauth/token"
              data = {
                  "client_id": client_id,
                  "client_secret": client_secret,
                  "grant_type": "client_credentials"
              }
              response = requests.post(url, data=data)
              return response.json().get("access_token")
          
          def create_tailscale_ephemeral_key(token: str):
              """
              Create a new tailscale ephemeral key
              """
              url = "https://api.tailscale.com/api/v2/tailnet/-/keys"
              headers = {
                  "Authorization": f"Bearer {token}"
              }
              data = {
                  "capabilities": {
                      "devices": {
                          "create": {
                              "reusable": True,
                              "ephemeral": True,
                              "preauthorized": True,
                              "tags": [ "tag:nix" ]
                          }
                      }
                  },
                  "description": "Nix token"
              }
          
              response = requests.post(url, headers=headers, json=data)
              return response.json().get("key")
          
          
          def parse_nix_file(path):
              # Run nix in a subprocess to evaluate the file as JSON
              result = subprocess.run(
                  ["nix", "eval", "--json", "-f", path], 
                  stdout=subprocess.PIPE, 
                  check=True, 
                  text=True
              )
              
              # Convert the JSON string to a Python dictionary
              data = json.loads(result.stdout)
              return data
          
          
          
          # 1. Retrieve the tailscale oauth client details by using the doppler api to retrieve the secrets
          tailscale_client_id = os.environ["TS_CLIENT_ID"]
          tailscale_client_secret = os.environ["TS_CLIENT_SECRET"]
          
          # 2. Use the tailscale oauth client details to authenticate with tailscale
          access_token = get_tailscale_api_token(tailscale_client_id, tailscale_client_secret)
          
          # 3. Create a new tailscale ephemeral key
          ephemeral_key = create_tailscale_ephemeral_key(access_token)
          
          secrets_config = parse_nix_file("secrets/secrets.nix")
          tailscale_keys = secrets_config["tailscale.age"]["publicKeys"]
          age_keys = []
          
          for key in tailscale_keys:
              if key.startswith("age"):
                  age_keys.append(x25519.Recipient.from_str(key))
              elif key.startswith("ssh"):
                  age_keys.append(ssh.Recipient.from_str(key))
          
          encrypted = encrypt(ephemeral_key, age_keys)
          
          f = open("secrets/tailscale.age", "w")
          f.write(encrypted)
          f.close()
          
          print("Updated tailscale.age with new ephemeral key")
        shell: python

      - name: Commit and PR
        run: |
          git config user.name "Tiebe Groosman"
          git config user.email "tiebe.groosman@gmail.com"
          git checkout -b tailscale-update
          git add secrets/tailscale.age
          git commit -m "Update tailscale key"
          git push origin tailscale-update

          gh pr create \
            --title "Update tailscale key" \
            --body "Update tailscale key" \
            --head tailscale-update \
            --base main
